### PR TITLE
Fix debugging #125

### LINKED ISSUE #125: Ruby debug error
**Excepted result:**
Debug process should Successfully disconnected.

**Actual result:**
Its throwing below errors
```
# Specification Heading
  ## Vowel counts in single word
Error ----------------------------------

[Gauge]
Connection to runner with Pid 28273 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:62056->127.0.0.1:62057: use of closed network connection

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 1.0.6.nightly-2019-07-19, c215a9f
	csharp (0.10.5), dotnet (0.1.1), html-report (4.0.8), java (0.7.2), js (2.3.5), python (0.3.5), ruby (0.5.3), screenshot (0.0.1), xml-report (0.2.1)
Error: Tests failed.
```
**Steps to reproduce:**

1. Create a ruby project
    `gauge init ruby`
2. open project in vs-code 
3. Put a debug point for any Scenario
3. Debug scenario    
4. click on disconnect button of debugger tool

### PR DESCRIPTION
**Pull request by BugDiver**
Fixes #125

### CODE REVIEW

File: lib/executor.rb [hunk 1]
```diff
@@ -10,7 +10,7 @@
 
 module Gauge
   class DebugOptions
-    attr_accessor :host, :port, :notify_dispatcher
+    attr_accessor :host, :port, :notify_dispatcher, :socket_path, :skip_wait_for_start
```
Comment (sriv) [inline lib/executor.rb:13]: do we need the `socket_path` accessor? it's not used anywhere

Comment (BugDiver) [reply lib/executor.rb:13]: We do not need it, but it's used by the debugger gem. And the access of it does not have a safety check. So we need to have this.
